In [31]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [32]:
updf_data = pd.read_csv('./13_Feb_UPDF.csv').reset_index()
kitara_data = pd.read_csv('./13_Feb_Kitara.csv').reset_index()

In [33]:
match_data = pd.concat([updf_data,kitara_data]).reset_index()

In [34]:
match_data['Team'] = match_data['Team'].fillna('').str.strip()
match_data['Team'] = match_data['Team'].apply(lambda x: 'UPDF' if 'UPDF' in x or 'UPF' in x else 'Kitara')

match_data['Player Name'] = match_data['Player Name'].fillna('').str.strip().str.title()
match_data['Position'] = match_data['Position'].str.strip().str.upper()
match_data['Position'] = match_data['Position'].apply(lambda x: 'FW' if 'FWD' in x else x )


match_data.drop(match_data.columns[23:],axis='columns',inplace=True)
match_data.drop(['Date','Split Start Time','Split End Time','Hr Load','Time In Red Zone (min)','index','Hr Max (bpm)'],axis='columns',inplace=True)
match_data.columns = match_data.columns.str.lower().str.replace(' ', '_')

In [44]:
match_data.drop('level_0',axis='columns',inplace=True);

In [45]:
match_data.shape
match_data.describe()

,duration,distance_(km),sprint_distance_(m),power_plays,energy_(kcal),impacts,player_load,top_speed_(km/h),distance_per_min_(m/min),power_score_(w/kg),work_ratio,max_deceleration_(m/s/s)
count,35.000000,35.000000,35.000000,35.000000,35.00000,35.000000,35.000000,35.000000,35.000000,35.000000,35.000000,35.000000
mean,11372.428571,8.171754,618.985429,42.942857,960.09964,8.057143,417.799389,27.730266,43.312297,3.348591,15.783051,6.674180
std,687.612121,3.720999,479.118699,30.266408,457.16799,8.058400,149.145561,4.935081,19.714129,1.576502,9.328646,1.152772
min,9712.000000,2.286300,0.000000,0.000000,247.34470,0.000000,159.483500,14.848100,12.047900,0.885200,1.498500,4.404500
25%,11089.000000,5.290100,208.020500,15.000000,622.41065,2.500000,296.382850,26.724200,28.199250,2.177900,7.393850,5.862250
50%,11420.000000,8.619200,584.574000,43.000000,990.05740,6.000000,440.486600,29.216200,50.293200,3.792300,16.892200,6.848900
75%,11849.500000,10.888600,923.566500,67.000000,1331.42550,11.000000,515.914950,31.064250,60.336250,4.677800,23.719200,7.585300
max,12678.000000,14.285000,1772.348000,98.000000,1687.48970,37.000000,700.520300,33.248300,70.142900,5.571500,30.698200,8.454000

In [ ]:
corr_df = match_data.corr(numeric_only=True)
sns.heatmap(corr_df);

In [53]:
# Select only numeric columns
numeric_cols = match_data.select_dtypes(include=[np.number]).columns

# Group by position and aggregate by mean
position_grouped = match_data.groupby('position')[numeric_cols].mean().reset_index()

# Group by team and aggregate by mean
team_grouped = match_data.groupby('team')[numeric_cols].mean().reset_index()

In [54]:
position_grouped

,position,duration,distance_(km),sprint_distance_(m),power_plays,energy_(kcal),impacts,player_load,top_speed_(km/h),distance_per_min_(m/min),power_score_(w/kg),work_ratio,max_deceleration_(m/s/s)
0,AM,11487.333333,8.895033,580.425167,44.500000,1022.452567,6.833333,448.533550,26.416183,46.668883,3.593383,18.349133,6.631217
1,CB,11402.166667,8.100683,449.573500,35.833333,998.729300,7.833333,412.863267,24.813517,42.775533,3.278717,16.054150,6.296100
2,DM,11585.666667,12.377067,917.427667,79.333333,1455.255600,5.000000,552.787667,28.928200,64.000000,4.997800,25.922267,6.881733
3,FW,11202.400000,6.564940,601.399200,39.600000,774.121440,5.200000,345.849880,29.670620,35.752580,2.787800,11.770200,6.630760
4,GK,11483.333333,5.729333,42.442333,5.666667,612.062567,11.000000,332.602500,25.269533,30.006467,2.172100,6.863867,6.029167
5,LB,12410.000000,13.491100,1710.987000,96.000000,1642.143400,37.000000,700.520300,31.504300,65.226900,5.273100,25.801000,7.966700
6,LW,11182.000000,5.039167,221.948667,17.000000,577.467433,3.000000,304.529867,25.090867,28.011133,2.107500,8.411833,6.235600
7,MF,11302.333333,6.851767,623.909667,41.666667,805.996667,7.333333,357.247467,28.832200,36.271167,2.833367,13.599367,6.902800
8,RB,11914.000000,12.750400,1182.793000,73.000000,1487.727400,26.000000,644.407600,31.368300,64.212000,4.976000,23.312500,8.454000
9,RF,11095.000000,6.950600,855.388000,43.000000,814.981000,7.000000,371.030300,33.248300,37.587500,2.927200,10.781900,6.848900
10,RW,10869.000000,9.342767,1103.716333,60.000000,1102.863467,6.333333,455.962533,31.448233,52.869433,4.173500,20.949567,7.153700

In [48]:
team_grouped

,team,duration,distance_(km),sprint_distance_(m),power_plays,energy_(kcal),impacts,player_load,top_speed_(km/h),distance_per_min_(m/min),power_score_(w/kg),work_ratio,max_deceleration_(m/s/s)
0,Kitara,11147.333333,8.273193,701.978733,47.733333,989.292993,7.733333,398.744260,29.665287,44.647180,3.480007,16.952833,6.760253
1,UPDF,11541.250000,8.095675,556.740450,39.350000,938.204625,8.300000,432.090735,26.279000,42.311135,3.250030,14.905715,6.609625

In [58]:
# Select only numeric columns
numeric_cols = match_data.select_dtypes(include=[np.number]).columns

# Group by position and aggregate by mean
position_grouped_by_team = match_data.groupby(['team','position'])[numeric_cols].mean()
position_grouped_by_team

                     duration  distance_(km)  sprint_distance_(m)  \
team   position
Kitara AM        10582.000000       8.870000           584.574000
       CB        11042.000000      10.592200           679.131667
       DM        11268.000000      11.423100           791.170500
       FW        11267.000000       5.533200           590.352667
       GK        11162.000000       5.877000            54.848000
       MF        11302.333333       6.851767           623.909667
       RF        11095.000000       6.950600           855.388000
       RW        11001.000000      10.622600          1772.348000
UPDF   AM        11668.400000       8.900040           579.595400
       CB        11762.333333       5.609167           220.015333
       DM        12221.000000      14.285000          1169.942000
       FW        11105.500000       8.112550           617.969000
       GK        11644.000000       5.655500            36.239500
       LB        12410.000000      13.491100          1710.987000
       LW        11182.000000       5.039167           221.948667
       RB        11914.000000      12.750400          1182.793000
       RW        10803.000000       8.702850           769.400500

                 power_plays  energy_(kcal)    impacts  player_load  \
team   position
Kitara AM          42.000000    1040.957500  11.000000   447.700000
       CB          56.666667    1326.651100  11.666667   483.378800
       DM          73.500000    1339.138550   4.500000   507.137650
       FW          37.000000     664.783000   4.666667   284.693700
       GK           4.000000     631.992600  14.000000   313.150300
       MF          41.666667     805.996667   7.333333   357.247467
       RF          43.000000     814.981000   7.000000   371.030300
       RW          74.000000    1280.894400   4.000000   459.048100
UPDF   AM          45.000000    1018.751580   6.000000   448.700260
       CB          15.000000     670.807500   4.000000   342.347733
       DM          91.000000    1687.489700   6.000000   644.087700
       FW          43.500000     938.129100   6.000000   437.584150
       GK           6.500000     602.097550   9.500000   342.328600
       LB          96.000000    1642.143400  37.000000   700.520300
       LW          17.000000     577.467433   3.000000   304.529867
       RB          73.000000    1487.727400  26.000000   644.407600
       RW          53.000000    1013.848000   7.500000   454.419750

                 top_speed_(km/h)  distance_per_min_(m/min)  \
team   position
Kitara AM               29.544200                 50.293200
       CB               30.162900                 57.615033
       DM               28.160200                 60.933400
       FW               28.829533                 29.591367
       GK               29.824200                 31.591200
       MF               28.832200                 36.271167
       RF               33.248300                 37.587500
       RW               32.568300                 57.936300
UPDF   AM               25.790580                 45.944020
       CB               19.464133                 27.936033
       DM               30.464200                 70.133200
       FW               30.932250                 44.994400
       GK               22.992200                 29.214100
       LB               31.504300                 65.226900
       LW               25.090867                 28.011133
       RB               31.368300                 64.212000
       RW               30.888200                 50.336000

                 power_score_(w/kg)  work_ratio  max_deceleration_(m/s/s)
team   position
Kitara AM                  3.920000   21.288600                  7.675600
       CB                  4.480400   23.572433                  6.989167
       DM                  4.745400   25.226850                  6.235900
       FW                  2.341567   10.155133                  6.128267
       GK                  2.256200    5.513400                  5.946700
       MF                  2.833367   13.599367                  6.902800
       RF                  2.927200   10.781900                  6.848900
       RW                  4.639900   24.274100                  8.400100
UPDF   AM                  3.528060   17.761240                  6.422340
       CB                  2.077033    8.535867                  5.603033
       DM                  5.502600   27.313100                  8.173400
       FW                  3.457150   14.192800                  7.384500
       GK                  2.130050    7.539100                  6.070400
       LB                  5.273100   25.801000                  7.966700
       LW                  2.107500    8.411833                  6.235600
       RB                  4.976000   23.312500                  8.454000
       RW                  3.940300   19.287300                  6.530500